# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[cmd_duration]
min_time = 1_000
show_milliseconds = true
format = "took [$duration](bold yellow)"

[directory]
truncation_length = 10
truncation_symbol = "::"
repo_root_style = "bold red"
use_os_path_sep = false

[git_branch]
symbol = "ğŸŒ± "
style = "bold green"

[git_commit]
commit_hash_length = 5
tag_symbol = " ğŸ”–"
only_detached = false
style = "bold blue"

[hostname]
ssh_symbol = "ğŸŒ "
